version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgresdb
    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ams-database

    ports:
      - 5432:5433
