services:
  ams-postgres-db:
    image: postgres:13
    container_name: ams-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: amsdb
    ports:
      - "5449:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ams-network

volumes:
  postgres_data:

networks:
  ams-network:
    external: true