"""added a status enum field in user

Revision ID: 2309f3af456c
Revises: 35567c611eb4
Create Date: 2024-09-01 21:26:29.380211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2309f3af456c'
down_revision: Union[str, None] = '35567c611eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'INACTIVE', name='status').create(op.get_bind())
    op.add_column('users', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='status', create_type=False), server_default='INACTIVE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    sa.Enum('ACTIVE', 'INACTIVE', name='status').drop(op.get_bind())
    # ### end Alembic commands ###
